server:
  port: ${SERVER_PORT:9040}

spring:
  application:
    name: fase4-users
  profiles:
    active: default

---
spring:
  config:
    activate:
      on-profile: default

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: as
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console


